# Generated by Django 2.1.3 on 2019-09-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=30)),
                ('productPrice', models.IntegerField()),
            ],
        ),
    ]
